project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('url_service.urls', namespace='url_service')),
    url(r'^admin/', include(admin.site.urls)),
]

url_service/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<short_url>[0-9A-Za-z]+)/$', views.redirect, name='redirect'),
    url(r'^(?P<short_url>[0-9A-Za-z]+)/inflate/$', views.inflate, name='inflate'),
]

url_service/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class URLMapper(models.Model):
	short_url = models.CharField(max_length=16, unique=True)
	long_url = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return "%d-%s-%s" % (self.pk, self.short_url, self.long_url)

url_service/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .helpers import generate_random_string, is_valid_URL
from .models import URLMapper

# Create your views here.
def index(request):
	if request.method == "GET":
		return render(
			request=request, 
			template_name='shortener_form.html'
		)
	elif request.method == "POST":
		long_url = request.POST['long_url'].strip()
		if not is_valid_URL(long_url):
			bundle = {
				'long_url': long_url,
				'error_msg': "Please enter a valid URL"
			}
			return render(
				request=request, 
				template_name='shortener_form.html', 
				context=bundle,
				status=400,
			)
		else:
			try:
				# if this long_url is alrady present in our DB, we won't create another short URL for it
				urlmapper_obj = URLMapper.objects.get(long_url=long_url)
			except URLMapper.DoesNotExist:
				created = False
				while not created:
					# In highly improbable / unlikely cases,
					# if our generated random string collides with an already existing short_url in DB,
					# we will keep retrying until get_or_create() returns created=True
					urlmapper_obj, created = URLMapper.objects.get_or_create(
						short_url=generate_random_string(),
						defaults={
							'long_url': long_url
						}
					)
			return HttpResponseRedirect(
				reverse('url_service:inflate', args=(urlmapper_obj.short_url,))
			)
	else:
		return HttpResponse(
			content = "<b>restricted attempt</b>",
			content_type = "text/html",
			status = 400
		)

def redirect(request, short_url):
	try:
		urlmapper_obj = URLMapper.objects.get(short_url=short_url)
	except URLMapper.DoesNotExist:
		bundle = {
			'error_msg': "Requested short URL not found"
		}
		return render(
			request=request, 
			template_name='shortener_form.html', 
			context=bundle,
			status=404,
		)
	else:
		return HttpResponseRedirect(urlmapper_obj.long_url)

def inflate(request, short_url):
	try:
		urlmapper_obj = URLMapper.objects.get(short_url=short_url)
	except URLMapper.DoesNotExist:
		bundle = {
			'error_msg': "Requested short URL not found"
		}
		return render(
			request=request, 
			template_name='shortener_form.html', 
			context=bundle,
			status=404,
		)
	else:
		bundle = {
			'short_url': request.build_absolute_uri(
				reverse('url_service:redirect', args=(urlmapper_obj.short_url,))
			),
			'long_url': urlmapper_obj.long_url,
		}
		return render(
			request=request, 
			template_name='shortener_form.html', 
			context=bundle
		)

templates/shortener_form.html
<html>
	<head>
		<title>Shorten URL</title>
		<style>
			button{
				padding: 10px;
				width: 225px;
				font-size: 15;
				display: block;
			}
			#error_block{
				background-color: #f00;
				color: #fff;
				padding: 10px;
				margin: 20px;
				width: 350px;
			}
			input{
				margin: 5px;
			}
			input[type="text"]{
				padding: 10px;
				text-align: center;
				font-size: 14;
				max-width: 100%;
			}
			input[name="long_url"]{
				background-color: lightyellow;
			}
			input[name="short_url"]{
				background-color: #eee;
			}
		</style>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body>
		<center>
			{% if error_msg %}
				<p id="error_block">
					<strong>{{ error_msg }}</strong>
				</p>
			{% endif %}
			<h1>Type in a URL to shorten it</h1>
			<form action="{% url 'url_service:index' %}" method="post">
				{% csrf_token %}
				<p>
					Your URL: <br />
					<input type="text" name="long_url" size="128" {% if long_url %}value="{{ long_url}}"{% endif %} />
				</p>
				<p>
					Generated short URL: <br />
					<input type="text" name="short_url" size="128" {% if short_url %}value="{{ short_url}}"{% endif %} readonly />
				</p>
				<p>
					{% if long_url and not error_msg %}
						Your URL: <b>{{ long_url|length }} characters</b>
					{% endif %}
				</p>
				<p>
					{% if short_url and not error_msg  %}
						Shortened URL: <b>{{ short_url|length }} characters</b>
					{% endif %}
				</p>
				<p>
					{% if short_url %}
						<button type="submit">Shorten again</button>
						&nbsp;&nbsp;
						<button 
							type="button" 
							onclick="window.location.href='{% url 'url_service:index' %}'"
						>
							Clear form
						</button>
						&nbsp;&nbsp;
						<button 
							type="button" 
							onclick="window.location.href='{{ short_url }}'"
						>
							Visit short URL
						</button>
					{% else %}
						<button type="submit">Shorten URL</button>
					{% endif %}
				</p>
			</form>
			<hr style="margin-top:30px;" />
			<div>
				Source code available<br />
				on <a 
					href="https://github.com/syedrakib/shorturl-django" 
					target="_blank"
				>Github</a>.
			</div>
		</center>
	</body>
</html>